### ISSUE TITLE
Player current server is not working

### ISSUE THREAD

**Issue by antoinech2** [Skungee/Skungee#100]
Hello, I've a problem with the "current bungee server" expression:

Try : `send "%player's current bungee server%"` or `current bungee server of "antoinech"`
Output: `<none>`

All other Skungee's syntax are working (most of them), but I can't use this.

However, the "bungee players" expression works well.
How can I fix this problem?

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.12 #46 duplicate
