### ISSUE TITLE
Error on start of bungee

### ISSUE THREAD

**Issue by ssaa1122** [Skungee/Skungee#115]
19:14:59 [INFO] [Skungee] Stack trace:
19:14:59 [INFO] [Skungee] java.net.BindException: Permission denied (Bind failed)
19:14:59 [INFO] [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
19:14:59 [INFO] [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
19:14:59 [INFO] [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:375)
19:14:59 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:237)
19:14:59 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:128)
19:14:59 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:150)
19:14:59 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:116)
19:14:59 [INFO] [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
19:14:59 [INFO] [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
19:14:59 [INFO] [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
19:14:59 [INFO] [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:14:59 [INFO]
19:14:59 [INFO] [Skungee] Information:
19:14:59 [INFO] [Skungee] Skungee: 1.0.11
19:14:59 [INFO] [Skungee] Bungee: git:BungeeCord-Bootstrap:1.15-SNAPSHOT:4cccf53:1426
19:14:59 [INFO] [Skungee] Game version: 1.8.x-1.15.x
19:14:59 [INFO] [Skungee] Protocol version: 573
19:14:59 [INFO] [Skungee] Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
19:14:59 [INFO] [Skungee] OS: Linux amd64 4.15.0-60-generic
19:14:59 [INFO]
19:14:59 [INFO] [Skungee] Thread: Thread[main,5,main]
19:14:59 [INFO] [Skungee] Cause: [ServerSocket couldn't be created on port: 1000]

**Comment by TheLimeGlass** [comment]
Try a different port, your server did not allow port 1000 to be binded. If on a hosting service, they may have this blocked or the port is already in use.
