### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by bloggy** [Skungee/Skungee#121]
I am unable to get the plugin loaded on 1.13.2. I get this on the spigot servers:
https://pastebin.com/XXAx2wqj

**Comment by TheLimeGlass** [comment]
Can you replicate this error on the latest Spigot and Bungeecord?

**Comment by bloggy** [comment]
What do you mean by latest spigot? My server runs in 1.13.2, which is of course not the latest spigot. We are also using waterfall instead of bungeecord.

**Comment by TheLimeGlass** [comment]
Potentially fixed in 1.0.12
