### ISSUE TITLE
Bungee load issues

### ISSUE THREAD

**Issue by ssaa1122** [Skungee/Skungee#123]
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] [Skungee] Severe Error: [ServerSocket couldn't be created on port: 1000]
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] Something went wrong within Skungee.
11:13:52 [INFO] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] Stack trace:
11:13:52 [INFO] [Skungee] java.net.BindException: Permission denied (Bind failed)
11:13:52 [INFO] [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
11:13:52 [INFO] [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
11:13:52 [INFO] [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:375)
11:13:52 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:237)
11:13:52 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:128)
11:13:52 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:150)
11:13:52 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:116)
11:13:52 [INFO] [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
11:13:52 [INFO] [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
11:13:52 [INFO] [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
11:13:52 [INFO] [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] Information:
11:13:52 [INFO] [Skungee] Skungee: 1.0.11
11:13:52 [INFO] [Skungee] Bungee: git:BungeeCord-Bootstrap:1.15-SNAPSHOT:7ed4c41:1431
11:13:52 [INFO] [Skungee] Game version: 1.8.x-1.15.x
11:13:52 [INFO] [Skungee] Protocol version: 575
11:13:52 [INFO] [Skungee] Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
11:13:52 [INFO] [Skungee] OS: Linux amd64 4.15.0-72-generic
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] Thread: Thread[main,5,main]
11:13:52 [INFO] [Skungee] Cause: [ServerSocket couldn't be created on port: 1000]
11:13:52 [INFO]
11:13:52 [INFO] [Skungee] End of Error.
11:13:52 [INFO]

**Comment by TheLimeGlass** [comment]
Server denied the socket to be created at the port, try a different port, or if using a hoster, find which ports they have allowed.
