### ISSUE TITLE
Error : Player is online on the Bungeecord

### ISSUE THREAD

**Issue by Acenox** [Skungee/Skungee#131]
Hello,, I just updated my server to SkUngee 1.0.12, but a syntax no longer seems to work with the new version and I can't understand, would you help me?
```
  loop {guarden.stafflist::*}:
    if bungee "%loop-value%" is online the bungee:
      broadcast "yes"
```
When I do this, I get a console error : <https://pastebin.com/UzC9MJaQ>
Thanks you :)

**Comment by TheLimeGlass** [comment]
Make sure your Spigot Skungee is the same version as the Bungeecord Skungee, I just looked at the erroring code and it can't happen unless the two versions are different, the latest 1.0.12 changed this code and both the Bungeecord Skungee and Spigot Skungee must be the same version.
