### ISSUE TITLE
Network Variables not being set

### ISSUE THREAD

**Issue by Dakotaa** [Skungee/Skungee#135]
I'm having trouble with network variables. I'm trying to set them, but they don't seem to be actually saving. I've checked the variables.csv file in Skungee/variables/, and none of the set variables are actually added to the file.

For example, I'm trying to set a network variable in this part of a script:
http://skungee.com/gocuwayida.sql
and neither of the network variables are actually set. The message with the second network variable on the third line sends only "<none>".

I turned on debugging, and get the following in console when running the above script:
http://skungee.com/ivomemuxic.sql

Also possibly related, my global scripts are not always updating when I update the script in the Skungee/scripts file. It seems like they will update if the Spigot server was restartly recently, but a few minutes after being restarted, global scripts nearly never update when the script in the Skungee file is updated.

**Comment by TheLimeGlass** [comment]
You set the variable `{votrewards}` and you're trying to get `{voterewards}` you spelt it wrong when getting the variable.
```
[Server] INFO [Skungee] Sending packet: NETWORKVARIABLE with data: name=votrewards, [type=long, data=[0, 0, 0, 0, 0, 0, 0, 1]] with change mode: SET
[Server] INFO [Skungee] Sending packet: NETWORKVARIABLE with data: voterewards
```
```
set network variable {votrewards} to 1
send "%network variable {voterewards}%" to arg-offlineplayer
```

**Comment by TheLimeGlass** [comment]
Thanks for the report, and providing all the proper information.

If you need further help, please create a new issue.

- Skungee team
