### ISSUE TITLE
Huge Error trying to create a network variable

### ISSUE THREAD

**Issue by GemsMC** [Skungee/Skungee#138]
http://skungee.com/fewakihexe.md

Caused by trying to create a Network variable

My Skript in the scripts Folder of skungee:

http://skungee.com/ojasisijap.cpp

**Comment by ManuGooX** [comment]
This happened to me, try this version 1.0.10b

https://forums.skunity.com/resources/skungee-the-bungeecord-addon-for-skript.87/download?version=2035

**Comment by TheLimeGlass** [comment]
Try Skript 2.5

**Comment by GemsMC** [comment]
Can't use Skript 2.5 because my spigot is on 1.12.2 means the latest Skript Version I can use is v2.3.6

**Comment by ManuGooX** [comment]
Did you remove all skungee folders and replace in all your servers that version of skungee?

**Comment by GemsMC** [comment]
Yes

**Comment by TheLimeGlass** [comment]
Skript issue not Skungee.
