### ISSUE TITLE
Connection problem Skungee Pterodactyl

### ISSUE THREAD

**Issue by manze2709** [Skungee/Skungee#144]
Hello i don`t can connect my paper sevrer whit Skungee to my bungeecord server whit skungee i use Pterodactyl

on the paper server:
> [17:35:28 INFO]: [Skungee] There was no socket found or was denied access at 172.18.0.1:1337
> [17:35:28 INFO]: [Skungee] Going into keep alive mode...

on the bungecord server:
16:13:43 [INFO] [Skungee] Connection established on address 0.0.0.0 with port 1337
16:13:43 [INFO] [Skungee] Skungee has been enabled!

i have also try localhost ther server ip put nothing works
thanks for help

**Comment by Hostilic** [comment]
Did you allocate the port 1337 on the proxy node? + Did you setup a receiver port and allocated that as well?

**Comment by manze2709** [comment]
what you mean if i open the porty on the proxy?

**Comment by manze2709** [comment]
not its working put its came this error



> 14:29:20 [INFO] [/207.180.228.237:33610] <-> InitialHandler has pinged
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] [Skungee] Severe Error: [Could not read incoming packet]
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] Something went wrong within Skungee.
> 14:29:22 [INFO] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] Stack trace:
> 14:29:22 [INFO] [Skungee] java.io.EOFException
> 14:29:22 [INFO] [Skungee] at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2736)
> 14:29:22 [INFO] [Skungee] at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3211)
> 14:29:22 [INFO] [Skungee] at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:896)
> 14:29:22 [INFO] [Skungee] at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
> 14:29:22 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:54)
> 14:29:22 [INFO] [Skungee] at java.lang.Thread.run(Thread.java:748)
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] Information:
> 14:29:22 [INFO] [Skungee] Skungee: 1.0.10b
> 14:29:22 [INFO] [Skungee] Bungee: git:BungeeCord-Bootstrap:1.15-SNAPSHOT:f1c32f8:1489
> 14:29:22 [INFO] [Skungee] Game version: 1.8.x-1.15.x
> 14:29:22 [INFO] [Skungee] Protocol version: 578
> 14:29:22 [INFO] [Skungee] Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
> 14:29:22 [INFO] [Skungee] OS: Linux amd64 4.15.0-91-generic
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] Thread: Thread[Thread-32,5,Skungee]
> 14:29:22 [INFO] [Skungee] Cause: [Could not read incoming packet]
> 14:29:22 [INFO]
> 14:29:22 [INFO] [Skungee] End of Error.

**Comment by zulu14** [comment]
hello, on peterodactyl you need to add an second port allocation , the default container system not allow multiple container to directlty talk.

CurseHosting.fr Manager

**Comment by manze2709** [comment]
Okey thanks
