### ISSUE TITLE
Checking if server is online causes internal server error

### ISSUE THREAD

**Issue by staridiot** [Skungee/Skungee#145]
Minecraft: 1.15.2
BungeeCord: Build 1487
Waterfall: 326
Paper: 143
Spigot: git-Spigot-6de3d4b-a6f8093
Skungee: 1.0.13

Console error: https://pastebin.com/wit1akaD
Script:
```
command /ison <text>:
	trigger:
		set {_server} to arg 1
		if server {_server} is online:
			message "yes"
		else:
			message "no"
```

Looks similar to #140

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/134
