### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Ofus-Will** [Skungee/Skungee#147]
Trigger: 
`
command /test:
    trigger:
        send "%connected bungeecord servers%"
`

Error:

> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! [Skript] Severe Error:
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Something went horribly wrong with Skript.
> [03:32:55 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
> [03:32:55 ERROR]: #!#! Your Minecraft version or server software appears to be unsupported by Skript (bensku's version).
> [03:32:55 ERROR]: #!#! Currently only supported servers are Spigot and its forks for Minecraft 1.9 or newer.
> [03:32:55 ERROR]: #!#! Other versions might work, but since you're getting this error message something is NOT working,
> [03:32:55 ERROR]: #!#! nor it will work, unless you switch to supported platform.
> [03:32:55 ERROR]: #!#! Issue tracker: https://github.com/SkriptLang/Skript/issues (only if you know what you're doing!)
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Stack trace:
> [03:32:55 ERROR]: #!#! java.lang.NullPointerException
> [03:32:55 ERROR]: #!#! at me.limeglass.skungee.spigot.elements.expressions.ExprBungeeServers.get(ExprBungeeServers.java:25)
> [03:32:55 ERROR]: #!#! at me.limeglass.skungee.spigot.elements.expressions.ExprBungeeServers.get(ExprBungeeServers.java:16)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:102)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.VariableString.toUnformattedString(VariableString.java:480)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.VariableString.getMessageComponents(VariableString.java:495)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.effects.EffMessage.execute(EffMessage.java:87)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.Effect.run(Effect.java:52)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute2(ScriptCommand.java:285)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.command.ScriptCommand.execute(ScriptCommand.java:242)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.command.Commands.handleCommand(Commands.java:257)
> [03:32:55 ERROR]: #!#! at ch.njol.skript.command.Commands$1.onPlayerCommand(Commands.java:172)
> [03:32:55 ERROR]: #!#! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [03:32:55 ERROR]: #!#! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [03:32:55 ERROR]: #!#! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [03:32:55 ERROR]: #!#! at java.lang.reflect.Method.invoke(Method.java:498)
> [03:32:55 ERROR]: #!#! at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:307)
> [03:32:55 ERROR]: #!#! at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
> [03:32:55 ERROR]: #!#! at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
> [03:32:55 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508)
> [03:32:55 ERROR]: #!#! at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1168)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:991)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
> [03:32:55 ERROR]: #!#! at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [03:32:55 ERROR]: #!#! at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:422)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:724)
> [03:32:55 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:627)
> [03:32:55 ERROR]: #!#! at java.lang.Thread.run(Thread.java:748)
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Version Information:
> [03:32:55 ERROR]: #!#! Skript: 2.2-dev36
> [03:32:55 ERROR]: #!#! Bukkit: 1.8.8-R0.2-SNAPSHOT
> [03:32:55 ERROR]: #!#! Minecraft: 1.8.8
> [03:32:55 ERROR]: #!#! Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
> [03:32:55 ERROR]: #!#! OS: Linux amd64 4.15.0-88-generic
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Server platform: Paper
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Current node: null
> [03:32:55 ERROR]: #!#! Current item: send "%ExprBungeeServers - [[(all [[of] the]|the)] [connected] bungee[[ ]cord] servers]%" to event-player/console
> [03:32:55 ERROR]: #!#! Current trigger: command /test (simple event) (bedwars.sk, line -1)
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Thread: Server thread
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! Language: english
> [03:32:55 ERROR]: #!#! Link parse mode: DISABLED
> [03:32:55 ERROR]: #!#!
> [03:32:55 ERROR]: #!#! End of Error.
> [03:32:55 ERROR]: #!#!

**Comment by TheLimeGlass** [comment]
Bungeecord version?

You should have an error in the Bungeecord.

Also you can use 1.15 Bungeecord, it doesn't define only 1.15 clients, all clients can join, it's just the version name for the time it came out.

**Comment by NikosDevMC** [comment]
Hey, i have the same bug.
My bungee version : latest (https://prnt.sc/rpjkd5)
My spigot version : 1.12.2
My skungee : 1.13
