### ISSUE TITLE
Online bungee player not working

### ISSUE THREAD

**Issue by PuchiGFX** [Skungee/Skungee#152]
Code: https://pastebin.com/XnHs78Wh
Error: https://pastebin.com/ifYZBSyi
Using PaperSpigot: git-Paper-172 (1.15.2 R01) and bungeecord BungeeCord-Bootstrap:1.15-SNAPSHOT:f1c32f8:1489
Skript version 2.4.1 and Skungee version 1.0.13

**Comment by PuchiGFX** [comment]
I just noticed i had this error when a player joins bungee
https://pastebin.com/q0yWp4Lh

**Comment by TheLimeGlass** [comment]
Please update your version, these have been fixed in 1.0.13.

**Comment by PuchiGFX** [comment]
Im already using that version :/
