### ISSUE TITLE
Error (ServerSocket couldn't be created on port: 1337)

### ISSUE THREAD

**Issue by mxgg** [Skungee/Skungee#154]
22:49:36 [INFO] [Skungee] [Skungee] Severe Error: [ServerSocket couldn't be created on port: 1337]
22:49:36 [INFO]
22:49:36 [INFO] [Skungee] Something went wrong within Skungee.
22:49:36 [INFO] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
22:49:36 [INFO]
22:49:36 [INFO] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
22:49:36 [INFO]
22:49:36 [INFO] [Skungee] Stack trace:
22:49:36 [INFO] [Skungee] java.net.BindException: Cannot assign requested address (Bind failed)
22:49:36 [INFO] [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
22:49:36 [INFO] [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
22:49:36 [INFO] [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:390)
22:49:36 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:252)
22:49:36 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:162)
22:49:36 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:124)
22:49:36 [INFO] [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
22:49:36 [INFO] [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
22:49:36 [INFO] [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
22:49:36 [INFO] [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

I'm getting this error and I have no clue what to do. Some help would be nice 👯

**Comment by TheLimeGlass** [comment]
This error happens because the port you have defined in the Skungee on Bungeecord to bind to, has been taken already, make sure you're setting the port option to an unused port that is port forwarded, typically a four digit port. You do not put the port of the Bungeecord proxy as the Skungee thread and Configuration tell you not to do.
