### ISSUE TITLE
bungee player is online

### ISSUE THREAD

**Issue by xYoowe** [Skungee/Skungee#158]
Server: paper 1.12.2
Skungee: 1.0.13
Bungeecord: waterfall (latest)

 command /test [&lt;offline player&gt;]:
	trigger:
		if bungeecord player arg is online:
			send "online" to player
		else:
			send "offline" to player

https://pastebin.com/xDg2uxsQ

**Comment by Govindass** [comment]
it only accepts online players and strings, not offline players, convert it to string or use uuid

**Comment by xYoowe** [comment]
also not working, same error

**Comment by xYoowe** [comment]
I also tried with the change: SkungeeReturn:" OFFLINEPLAYER "
sk: https://pastebin.com/2Cczpav0
errors: https://pastebin.com/wqdfBCB3

**Comment by TheLimeGlass** [comment]
Please update your Skungee, this error was fixed.
