### ISSUE TITLE
2 servers connecting but other doesnt

### ISSUE THREAD

**Issue by AlbieGames** [Skungee/Skungee#162]
my survival server connects to skungee but the lobby server which has the exact same config doesnt connect and just spammed this error in the console:
![image](https://user-images.githubusercontent.com/66000592/82987202-1534bf80-9fef-11ea-97cc-61480f569f3b.png)

**Comment by TheLimeGlass** [comment]
Make sure the configurations of each server are different, they can't be cloned. They need to follow the installation guide. Make sure receivers are on auto for ease of use, make sure the port points to the bungeecord port.
