### ISSUE TITLE
Player's bungeecord server returns <none>

### ISSUE THREAD

**Issue by JimmyTDM** [Skungee/Skungee#164]
So I'm using skungee 1.0.13 (latest version) and when I try to execute any skungee effect like send player or message player's bungeecord server it doesnt do anything, I tried downgrading to 1.0.12 and still, it doesn't work, any advice on what to do? /server works, but nothing else related to skungee with skript (in the bungeecord console it does work)

**Comment by TheLimeGlass** [comment]
Most likely a duplicate of #149 and others
