### ISSUE TITLE
error on enabling

### ISSUE THREAD

**Issue by ab3ata** [Skungee/Skungee#165]
hey i am getting this error when i start the server

09:05:41 [INFO] [Skungee] Stack trace:
09:05:41 [INFO] [Skungee] java.net.BindException: Cannot assign requested address (Bind failed)
09:05:41 [INFO] [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
09:05:41 [INFO] [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
09:05:41 [INFO] [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:390)
09:05:41 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:252)
09:05:41 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:162)
09:05:41 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:124)
09:05:41 [INFO] [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
09:05:41 [INFO] [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
09:05:41 [INFO] [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
09:05:41 [INFO] [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
09:05:41 [INFO]
09:05:41 [INFO] [Skungee] Information:
09:05:41 [INFO] [Skungee] Skungee: 1.0.13
09:05:41 [INFO] [Skungee] Bungee: git:BungeeCord-Bootstrap:1.15-SNAPSHOT:b91d4d3:1492
09:05:41 [INFO] [Skungee] Game version: 1.8.x-1.15.x
09:05:41 [INFO] [Skungee] Protocol version: 578
09:05:41 [INFO] [Skungee] Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
09:05:41 [INFO] [Skungee] OS: Linux amd64 4.4.0-178-generic
09:05:41 [INFO]
09:05:41 [INFO] [Skungee] Thread: Thread[main,5,main]
09:05:41 [INFO] [Skungee] Cause: [ServerSocket couldn't be created on port: 25565]
09:05:41 [INFO]
09:05:41 [INFO] [Skungee] End of Error.

**Comment by TheLimeGlass** [comment]
The port you're trying to bind too is already in use.

Please read the Skungee installation. The port of the Skungee Spigot is not the Bungeecord port.

The Skungee Spigot port option in the configuration needs to match the same port option in the Skungee Bungeecord configuration.
