### ISSUE TITLE
Players cannot connect to the network.

### ISSUE THREAD

**Issue by hswhsw610** [Skungee/Skungee#176]
It worked a few days ago...
But now, all players can't connect to the network. I'm quite confused now...
When I connect to server It shows this

`NoSuchMethodError : 'int net.md_5.bungee.protocol.packet.Login.getDimension()' @ me.limeglass.skungee.bungeecord.protocol.LoginPacketHandler:22`
->> [console log](http://skungee.com/qifarohile.bash) <<-

I'm using the latest version of everything.
I even delete all plugins except Skript and Skungee.... But it's still not working!!!
(Sorry for bad English XD)

**Comment by BestInTest** [comment]
If you use Waterfall try downgrade to build 350 (it worked for me).

**Comment by hswhsw610** [comment]
> If you use Waterfall try downgrade to build 350 (it worked for me).

I am not using Waterfall.....

**Comment by Zulfen** [comment]
Same here, perhaps there has been significant changes with BungeeCord that might have broken Skungee.

**Comment by ChoqueCastroLD** [comment]
[Skungee1.16.1BungeeFix.zip](https://github.com/Skungee/Skungee/files/4833690/Skungee1.16.1BungeeFix.zip)

I fixed it and compiled it myself, so this will do, there's only a small hardcoded bugfix, so don't rely on it, and update to the official version as soon as it's released

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.14
