### ISSUE TITLE
ProxyPingEvent issues

### ISSUE THREAD

**Issue by MrCrazyKill** [Skungee/Skungee#18]
Hi, i've a new error when i join my server

Server version: CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
Bungeecord version: latest

Error:
`20.08 04:05:22 [Server] ERROR Could not pass event PlayerJoinEvent to Skellett v1.9.6b
20.08 04:05:22 [Server] INFO org.bukkit.event.EventException
20.08 04:05:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.onPlayerJoin(PlayerList.java:314) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.a(PlayerList.java:173) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.b(LoginListener.java:144) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.LoginListener.c(LoginListener.java:54) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:231) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:148) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:875) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
20.08 04:05:22 [Server] INFO Caused by: java.util.NoSuchElementException: packet_handler
20.08 04:05:22 [Server] INFO at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150) ~[paperspigot.jar:git-PaperSpigot-"4c7641d"]
20.08 04:05:22 [Server] INFO at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:66) ~[?:?]
20.08 04:05:22 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:272) ~[?:?]
20.08 04:05:22 [Server] INFO at com.gmail.thelimeglass.Utils.Packets.PacketListener.create(PacketListener.java:70) ~[?:?]
20.08 04:05:22 [Server] INFO at com.gmail.thelimeglass.Utils.Packets.PacketListener.onJoin(PacketListener.java:22) ~[?:?]
20.08 04:05:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
20.08 04:05:22 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]`

**Comment by MrCrazyKill** [comment]
I've just see 2 errors in bungee console:

`20.08 04:04:00 [Server] WARNING Event ProxyPingEvent(connection=[/78.205.40.20:64835] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=BungeeCord 1.8.x-1.13.x, protocol=47), players=ServerPing.Players(max=100, online=0, sample=null), description=EverialMC - En attente du MOTD..., modinfo=ServerPing.ModInfo(type=FML, modList=[]))) took 250,202,332ns to process!`
`20.08 04:05:22 [Server] WARNING No client connected for pending server!
20.08 04:05:22 [Server] INFO java.lang.IllegalArgumentException: Unexpected packet received during server login process!
20.08 04:05:22 [Server] INFO 4101
20.08 04:05:22 [Server] INFO at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:130)
20.08 04:05:22 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
20.08 04:05:22 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
20.08 04:05:22 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)`

**Comment by TheLimeGlass** [comment]
Also putting this here 
```
java.lang.NoSuchFieldError: SUPPORTED_VERSION_IDS 20.08 02:57:02 [Server] INFO at me.limeglass.skungee.bungeecord.listeners.EventListener.onPing(EventListener.java:64) 20.08 02:57:02 
```

**Comment by TheLimeGlass** [comment]
Are you using a custom client or something? 
`Unexpected packet received during server login process!`

**Comment by TheLimeGlass** [comment]
This is Bungeecord erroring.

**Comment by TheLimeGlass** [comment]
Try updating your Bungeecord to the latest version, this is more of a Bungeecord issue than Skungee.

**Comment by TheLimeGlass** [comment]
Potentially fixed a few versions ago. Make a new issue if still present.
