### ISSUE TITLE
ServerSocket couldn't be created on port: 1024

### ISSUE THREAD

**Issue by Juan16236123** [Skungee/Skungee#199]
I have no idea why I am having this problem, nor can I find a solution's

Console Error: https://pastebin.com/3KZrJDtk

**Comment by Zulfen** [comment]
hi there, this is because you are most likely on a shared host and the port you are trying to bind to is already occupied - if you have an extra port given by your host, please use that!

**Comment by Juan16236123** [comment]
My server had a "Additional Ports" place, and I used the port and it didn't work

**Comment by TheLimeGlass** [comment]
duplicate #200
