### ISSUE TITLE
Setup bungeecord

### ISSUE THREAD

**Issue by GirafDrengen** [Skungee/Skungee#200]
20:21:10 [INFO] [Skungee] [Skungee] Severe Error: [ServerSocket couldn't be created on port: 1337]
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Something went wrong within Skungee.
20:21:10 [INFO] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Stack trace:
20:21:10 [INFO] [Skungee] java.net.BindException: Cannot assign requested address (Bind failed)
20:21:10 [INFO] [Skungee] at java.net.PlainSocketImpl.socketBind(Native Method)
20:21:10 [INFO] [Skungee] at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
20:21:10 [INFO] [Skungee] at java.net.ServerSocket.bind(ServerSocket.java:390)
20:21:10 [INFO] [Skungee] at java.net.ServerSocket.<init>(ServerSocket.java:252)
20:21:10 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.connect(Skungee.java:162)
20:21:10 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.Skungee.onEnable(Skungee.java:124)
20:21:10 [INFO] [Skungee] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:252)
20:21:10 [INFO] [Skungee] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:447)
20:21:10 [INFO] [Skungee] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:32)
20:21:10 [INFO] [Skungee] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Information:
20:21:10 [INFO] [Skungee] Skungee: 1.0.15
20:21:10 [INFO] [Skungee] Bungee: Aegis fork
20:21:10 [INFO] [Skungee] Game version: 1.7.x-1.16.x
20:21:10 [INFO] [Skungee] Protocol version: 736
20:21:10 [INFO] [Skungee] Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
20:21:10 [INFO] [Skungee] OS: Linux amd64 4.15.0-54-generic
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Thread: Thread[main,5,main]
20:21:10 [INFO] [Skungee] Cause: [ServerSocket couldn't be created on port: 1337]
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] End of Error.
20:21:10 [INFO]
20:21:10 [INFO] [Skungee] Skungee has been enabled!

**Comment by Anarchick** [comment]
Does your port 1337 allow connection ?

**Comment by GirafDrengen** [comment]
![image](https://user-images.githubusercontent.com/69653703/91585801-cf242a80-e954-11ea-8ef2-973ca261c081.png)

**Comment by GirafDrengen** [comment]
Dont think so

**Comment by GirafDrengen** [comment]
![image](https://user-images.githubusercontent.com/69653703/91585924-00045f80-e955-11ea-914e-4eec0411dbcf.png)

**Comment by TheLimeGlass** [comment]
You cannot reload Skungee, same with Skript.

**Comment by GirafDrengen** [comment]
So what to do?

**Comment by TheLimeGlass** [comment]
> Error is probably because you have the address already bound, or the ip you're allocating to bind too, isn't part of your system.
> 
> You cannot reload Skungee, same with Skript.

Change the port and/or ip
