### ISSUE TITLE
Skungee security ?

### ISSUE THREAD

**Issue by WhiteColors** [Skungee/Skungee#202]
Hello, 
I have a problem with Skungee and my servers. When I have skungee on bungeecord, it's "Connection established on address 0.0.0.0 with port 1337" and "Skungee has been enabled!". But in my server, it's "Reciever established on port 1337", "Some security settings didn't match for the incoming packet. Make sure all your security options on the Spigot servers match the same as in the Bungeecord Skungee configuration.yml. The packet could not be read, thus being cancelled." and always "Ping packet had no response, configurion for the connection to Bungeecord Skungee may not be valid or blocked. Attempting to try again... X/5" with "Sending packet: HANDSHAKE"...
Help please :c

**Comment by TheLimeGlass** [comment]
The receiver is different from the Skungee, the receiver port is for Spigot, each Spigot server needs one.
