### ISSUE TITLE
 [Error reading the PacketPlayInLook of packet null]

### ISSUE THREAD

**Issue by mathcover** [Skungee/Skungee#204]
paper 1.16.2
skript 2.5 b3
proxy error

19:00:06 [INFOS] [Skungee] Something went wrong within Skungee.
19:00:06 [INFOS] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
19:00:06 [INFOS] 
19:00:06 [INFOS] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
19:00:06 [INFOS] 
19:00:06 [INFOS] [Skungee] Stack trace:
19:00:06 [INFOS] [Skungee] java.lang.IndexOutOfBoundsException: readerIndex(0) + length(4) exceeds writerIndex(2): PooledUnsafeDirectByteBuf(ridx: 0, widx: 2, cap: 2)
19:00:06 [INFOS] [Skungee]     at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1477)
19:00:06 [INFOS] [Skungee]     at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:810)
19:00:06 [INFOS] [Skungee]     at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:857)
19:00:06 [INFOS] [Skungee]     at me.limeglass.skungee.bungeecord.protocol.handlers.ProtocolLookHandler.handlePacket(ProtocolLookHandler.java:39)
19:00:06 [INFOS] [Skungee]     at me.limeglass.skungee.bungeecord.protocol.channel.ChannelHandler.lambda$write$0(ChannelHandler.java:35)
19:00:06 [INFOS] [Skungee]     at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
19:00:06 [INFOS] [Skungee]     at me.limeglass.skungee.bungeecord.protocol.channel.ChannelHandler.write(ChannelHandler.java:35)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
19:00:06 [INFOS] [Skungee]     at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:57)
19:00:06 [INFOS] [Skungee]     at net.md_5.bungee.UserConnection.sendPacket(UserConnection.java:172)
19:00:06 [INFOS] [Skungee]     at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:128)
19:00:06 [INFOS] [Skungee]     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
19:00:06 [INFOS] [Skungee]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
19:00:06 [INFOS] [Skungee]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
19:00:06 [INFOS] [Skungee]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
19:00:06 [INFOS] [Skungee]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
19:00:06 [INFOS] [Skungee]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
19:00:06 [INFOS] [Skungee]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
19:00:06 [INFOS] [Skungee]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
19:00:06 [INFOS] [Skungee]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
19:00:06 [INFOS] [Skungee]     at java.base/java.lang.Thread.run(Thread.java:834)
19:00:06 [INFOS] 
19:00:06 [INFOS] [Skungee] Information:
19:00:06 [INFOS] [Skungee]   Skungee: 1.0.15
19:00:06 [INFOS] [Skungee]   Bungee: git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:aa22fe6:1530
19:00:06 [INFOS] [Skungee]   Game version: 1.8.x-1.16.x
19:00:06 [INFOS] [Skungee]   Protocol version: 751
19:00:06 [INFOS] [Skungee]   Java: 11.0.8 (OpenJDK 64-Bit Server VM 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
19:00:06 [INFOS] [Skungee]   OS: Linux amd64 4.15.0-112-generic
19:00:06 [INFOS] 
19:00:06 [INFOS] [Skungee] Thread: Thread[Netty IO Thread #10,5,main]
19:00:06 [INFOS] [Skungee] Cause: [Error reading the PacketPlayInLook of packet null]
19:00:06 [INFOS] 
19:00:06 [INFOS] [Skungee] End of Error.

**Comment by TheLimeGlass** [comment]
Disable Packets in the config.yml of Bungeecord. They're experimental, and not going to be supported in future versions.
