### ISSUE TITLE
Can't link servers with Pterodactyl Software Docker

### ISSUE THREAD

**Issue by ImAzyx** [Skungee/Skungee#209]
When i setup the skungee config for the bungeecord and servers, it doesn't work.

When servers are included in the docker we have this error :
> [14:34:10 INFO]: [Skungee] There was no socket found or was denied access at 172.18.0.1:27015
> [14:34:10 INFO]: [Skungee] Going into keep alive mode...

But when we exclude the server from the docker it works: 
> [Skungee] Connected to server server1 with port 27003

However, i can't let servers outside the docker. Is there a way to fix the problem please ?
Skungee seems to be very useful but I can't use it due to this problem.

**Comment by KeymZ-Development** [comment]
I have the same problem with the pterodactyl panel. Is there finally a solution to make skungee work on the pterodactyl panel or not? It is very problematic. :/

**Comment by ImAzyx** [comment]
Is there any way to talk with the creator of Skungee please ?

**Comment by KeymZ-Development** [comment]
In the skript chat discord https://discord.gg/0lx4QhQvwelCZbEX

**Comment by TheLimeGlass** [comment]
https://github.com/Skungee/Skungee/issues/227
