### ISSUE TITLE
Skungee error sending to server on bungeecord network

### ISSUE THREAD

**Issue by WaterChick** [Skungee/Skungee#213]
Hi,

I have an issue with skungee sending me from Lobby to BuildServer.

All my servers are connected successfully.

Lobby log: https://pastebin.com/7F5vcrPq
Bungeecord log: https://pastebin.com/1yULgQD7
BuildServer log: https://pastebin.com/UeE2SXiJ
Skript that should send me to buildserver: https://pastebin.com/x2gsQG7M

Lobby and Build server version: 
CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

Bungee version:
BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.4-SNAPSHOT:5ab5a84:1533 by md_5

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/156
