### ISSUE TITLE
All expressions and effects return <none> or stop working after a couple of hours

### ISSUE THREAD

**Issue by Zulfen** [Skungee/Skungee#215]
After around 3 or 4 hours, all Skungee expressions and effects stop working. The time it takes seems to vary on network conditions (?). Everything works fine before it randomly stops working.

You might be able to replicate this by setting up a Skungee installation and just waiting for a while.  This could be an issue with my VPS, but this has also occured on shared hosting.

Skript version: 2.5.1
Skungee version: 1.0.15
Backend servers: Paper-1618 (1.12.2)
Waterfall/Proxy version: Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:af18705:381

Backend Skungee config: https://pastebin.com/nGwDU9qs
Proxy config: https://pastebin.com/wdELyJkh

**Comment by TheLimeGlass** [comment]
Try Skungee 2.0.0 in the GitHub organization
