### ISSUE TITLE
Skungee packets

### ISSUE THREAD

**Issue by W0lfyZRex** [Skungee/Skungee#221]
So 2 of my servers are fine and exchange packets with bungee every 2 seconds but 1 server gets denied by the bungee (like it sends a HEARTBEAT packet and the bungee doesnt even show it or respond to it) so i cant warp people to other servers etc. and thats rlly annoying.

Could someone explain to me how to fix it?
![ddddddd](https://user-images.githubusercontent.com/66094336/100518629-97fb2a80-318a-11eb-9946-46bf937083bf.png)

(25565 and 25566 are completely fine [even tho they sometimes disconnected like 25567 in the past but it doesnt happen anymore] but 25567 just keeps sending heartbeat without response and the skungee effects dont work at all)

Edit : also this error happens sometimes
![ddddddd](https://user-images.githubusercontent.com/66094336/100518747-6c2c7480-318b-11eb-9b42-ccc5131e1646.png)

**Comment by TheLimeGlass** [comment]
Try Skungee 2.0.0

**Comment by W0lfyZRex** [comment]
Does Skungee 2.0 work with ServerInstances ? I also really want to make it to work :(
https://github.com/Skungee/ServerInstancesPlugin/issues/21
Ill try skungee 2.0 since my priority is not serverinstances

**Comment by W0lfyZRex** [comment]
![ddddddd](https://user-images.githubusercontent.com/66094336/100538385-5b314100-3227-11eb-9d89-bc1d29fa96d5.png)

**Comment by TheLimeGlass** [comment]
Skungee 2.0.0 requires Skript 2.3+

**Comment by TheLimeGlass** [comment]
https://github.com/Skungee/Skungee-2.0.0/issues/63
