### ISSUE TITLE
Skungee 1.0.15 Connection Error 

### ISSUE THREAD

**Issue by manze2709** [Skungee/Skungee#238]
Hello i have this error 

17:43:47 [INFO] [Skungee] Some security settings didn't match for the incoming packet.
17:43:47 [INFO] [Skungee] Make sure all your security options on the Spigot servers match the same as in the Bungeecord Skungee config.yml
17:43:47 [INFO] [Skungee] The packet could not be read, thus being cancelled.

 my file are ecual 

[Configs.zip](https://github.com/Skungee/Skungee/files/5966976/Configs.zip)

**Comment by manze2709** [comment]
17:55:58 [SEVERE] Exception in thread "Thread-20" 
17:55:58 [SEVERE] java.lang.NullPointerException
17:55:58 [SEVERE]     at me.limeglass.skungee.UniversalSkungee.getPacketDebug(UniversalSkungee.java:24)
17:55:58 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:70)
17:55:58 [SEVERE]     at java.lang.Thread.run(Thread.java:748)

**Comment by manze2709** [comment]
On skungee 1.0.10b everything works perfectly, only sometimes this error occurs and the network variables are deleted


46:10 [SEVERE] Exception in thread "Thread-7347" 
17:46:10 [SEVERE] Exception in thread "Thread-7348" 
17:46:10 [SEVERE] java.lang.NegativeArraySizeException
17:46:10 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
17:46:10 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
17:46:10 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
17:46:10 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
17:46:10 [SEVERE] java.lang.NegativeArraySizeException
17:46:10 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
17:46:10 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
17:46:10 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
17:46:10 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
17:46:10 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
17:58:53 [SEVERE] Exception in thread "Thread-13208" 
17:58:53 [SEVERE] java.lang.NegativeArraySizeException
17:58:53 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
17:58:53 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
17:58:53 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
17:58:53 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
17:58:53 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
17:58:53 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
17:58:53 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
17:58:53 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
17:58:53 [SEVERE]     at java.lang.Thread.run(Thread.java:74

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/239
