### ISSUE TITLE
Skungee 1.0.10b

### ISSUE THREAD

**Issue by manze2709** [Skungee/Skungee#239]
Hello i have this error on skungee 1.0.10b on 1.8.8 server

20:22:26 [SEVERE] Exception in thread "Thread-3105" 
20:22:26 [SEVERE] java.lang.NegativeArraySizeException
20:22:26 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
20:22:26 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
20:22:26 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
20:22:26 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
20:22:26 [SEVERE] Exception in thread "Thread-3104" 
20:22:26 [SEVERE] java.lang.NegativeArraySizeException
20:22:26 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
20:22:26 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
20:22:26 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
20:22:26 [SEVERE]     at java.lang.Thread.run(Thread.java:748)

20:22:26 [SEVERE] Exception in thread "Thread-3105" 
20:22:26 [SEVERE] java.lang.NegativeArraySizeException
20:22:26 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
20:22:26 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
20:22:26 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
20:22:26 [SEVERE]     at java.lang.Thread.run(Thread.java:748)
20:22:26 [SEVERE] Exception in thread "Thread-3104" 
20:22:26 [SEVERE] java.lang.NegativeArraySizeException
20:22:26 [SEVERE]     at java.util.AbstractCollection.toArray(AbstractCollection.java:136)
20:22:26 [SEVERE]     at java.util.ArrayList.<init>(ArrayList.java:178)
20:22:26 [SEVERE]     at com.google.common.collect.Lists.newArrayList(Lists.java:149)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.loadFromHash(FlatFileStorage.java:253)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.variables.FlatFileStorage.set(FlatFileStorage.java:225)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:52)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.handlers.NetworkVariableHandler.handlePacket(NetworkVariableHandler.java:15)
20:22:26 [SEVERE]     at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:117)
20:22:26 [SEVERE]     at java.lang.Thread.run(Thread.java:748)

i have tried a newer version put the network variabeln dont work, there are no errors and als server connects whit skungee

**Comment by TheLimeGlass** [comment]
The latest version is 1.0.25, this had been fixed in later versions.
