### ISSUE TITLE
Skunge 1.15 only only one works network variable

### ISSUE THREAD

**Issue by manze2709** [Skungee/Skungee#243]
Hello i my problem is that only one time works the network variable after the first time nothing works

Connected to server lobby with port 2000
19:35:04 [INFO] [Skungee] packet: HANDSHAKE is returning data: CONNECTED
19:35:04 [INFO] [Skungee] Recieved packet: NETWORKVARIABLE with data: name=<none>.o, [type=long, data=[0, 0, 0, 0, 0, 0, 0, 1]] with change mode: SET

**Comment by TheLimeGlass** [comment]
Try Skungee 2.0.0

**Comment by manze2709** [comment]
i have a 1.8.8 server

**Comment by TheLimeGlass** [comment]
Skungee 2.0.0 now works with 1.8 https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-ALPHA-17
