### ISSUE TITLE
How to install skungee on your minecraft server

### ISSUE THREAD

**Issue by Maxii-ui** [Skungee/Skungee#245]
title how do u install skungee, what host should i put? can someone expain

**Comment by TheLimeGlass** [comment]
1.) Place Skungee in your Bungeecord plugins folder and restart Bungeecord.
2.) Install Skungee on every other server connected to this Bungeecord that you want Skript support for, then restart those servers.
3.) Configure the Skungee.yml found at plugins/Skungee/config.yml to match the same port as the Skungee config found in the Bungeecord plugin folder. The Host option in the config.yml on the spigot servers should match the IP of your Bungeecord (Excluding the ip port)
