### ISSUE TITLE
After trying to save network variable all skungee function froze

### ISSUE THREAD

**Issue by Maxii-ui** [Skungee/Skungee#252]
hello, im having problem with variable when i try run this code:

if network variable {doubleexp::bedwars} is set:
	set {_doubleexp::players::*} to network variable "doubleexp::bedwars::players::*"
			
then all skungee expression just froze and are not working.. and i have to restart whole bungeecord and spigot servers (im running on localhost)

**Comment by TheLimeGlass** [comment]
`network variable {example::variable}` it's not a string.

**Comment by Maxii-ui** [comment]
Fixed.. but when i try:

set network variable {test} to "test" skungee frozes need restart whole bungeecord and servers.

**Comment by TheLimeGlass** [comment]
Use Skungee 2.0

**Comment by Maxii-ui** [comment]
Works! Tysm you're the best!
