### ISSUE TITLE
There was no socket found or was denied access at localhost:6969

### ISSUE THREAD

**Issue by W0lfyZRex** [Skungee/Skungee#262]
I've been trying to get Skungee to link between bungeecord and spigot server with the default config and then tried to edit the port, the ip, etc without success. It always says "There was no socket found or was denied access at X:Y" no matter the ip or the port. I'm pretty sure it's related to the fact that I use pterodactyl but I don't know how to fix this.

Bungee: 
![image](https://user-images.githubusercontent.com/66094336/131728303-59802df3-0219-4451-9b87-313fcd1d98d0.png)

Spigot: 
![image](https://user-images.githubusercontent.com/66094336/131728348-0ab49b48-5cc9-4b9c-9308-64647dde3e6f.png)

**Comment by TheLimeGlass** [comment]
Try Skungee 2.0

**Comment by W0lfyZRex** [comment]
How tf do I get Skungee 2.0??

**Comment by TheLimeGlass** [comment]
With the magic of television https://github.com/Skungee/Skungee-2.0.0/releases

**Comment by W0lfyZRex** [comment]
u r da best 😃

**Comment by W0lfyZRex** [comment]
Bruh, Skungee 2.0 requires Java 11 or more and the server won't start with anything else than Java 8.
![image](https://user-images.githubusercontent.com/66094336/131733116-ce4a4fb2-d4cc-4c79-ac0f-04ff8a30ee85.png)

The server just doesn't want to start.

**Comment by W0lfyZRex** [comment]
I know I could put vanilla spigot 1.8.8 but since I plan on having lots of servers (and I need them to not lag), I need to have a performance spigot fork on to avoid having to allocate like 2 cores per server for it to run properly

**Comment by W0lfyZRex** [comment]
Okay so I fixed the "i is not a recognized option" thing but skungee 2.0 still asks for an even higher java version (16 i assume), and imanityspigot does NOT support that.

Edit: tried using vanilla spigot 1.8.8 and half of the plugins don't load (including LuckPerms, WorldEdit, Skript, etc) because of Java 16

**Comment by W0lfyZRex** [comment]
I'm desperate. Tried every single version of Skungee, tried allocating the required ports to the bungee and the spigot server, tried changing java version, tried changing the spigot, tried everything. I do not know why it doesn't wanna connect. How can I try and troubleshoot the issue?

**Comment by TheLimeGlass** [comment]
When changing Java versions, it requires a restart, make sure the environmental variable for it points to Java 16. You can even just remove Java 8

**Comment by W0lfyZRex** [comment]
My servers are on pterodactyl so they are in a docker container, docker does it automatically

**Comment by W0lfyZRex** [comment]
Even with an older version of 2.0 that still supports Java 11, it just won't connect to skungee on the bungee

**Comment by W0lfyZRex** [comment]
Okay so I'm at a state where both plugins are working (using 1.x), the spigot plugin tries to connect to the bungee plugin by sending handshake packets with no success. I allocated the 1337 port to the bungee, allocated the 2000 port to the spigot server (for the receiver), tried a bunch of ips in the "host" field in the config of the spigot server and tried messing with the bungee skungee config too, but whenever i try to change "bind-to-address" to an ip that isn't local (so like localhost or 127.0.0.1 or 0.0.0.0) it just throws an error. I'm really confused why its not wanting to connect.

**Comment by W0lfyZRex** [comment]
Tried skungee 2.0 again and when the bungee starts theres this "SEVERE" line:
![image](http://ec2-18-118-197-146.us-east-2.compute.amazonaws.com/firefox_d7lsRLQH7q.png)

**Comment by W0lfyZRex** [comment]
Issue fixed, I put my bungeecord server in a linux screen instead of in a docker container, it fixed the issue.
