### ISSUE TITLE
set {_y::*} to all connected bungeecord servers return <none>

### ISSUE THREAD

**Issue by 0Sydes** [Skungee/Skungee#38]
I have a problem ;( i don't know why

`set {_y::*} to all of the connected bungeecord servers`
`broadcast "&e%{_y::*}%"`

always return none, when the plugin reload on bungee it say connected to server lobby with port 25569 so why it return none.

I also have another problem

`message "text" to all bungeecord players`

do nothing, no messages

`connect bungeecord player player to bungeecord server "TheServerName on /server"`

do nothing and don't teleport me.

I need help pls

**Comment by TheLimeGlass** [comment]
The players need to have joined through the proxy. The last syntax is messed up.

**Comment by Frost145** [comment]
I found how to teleport players to another server using `execute bungeecord proxy command "send %player% server"`

but i still have a problem with `message "test" to all bungeecord players`; i don't understand what you mean by "players need to have joined through the proxy". Can you help me pls?

**Comment by Frost145** [comment]
Well... I found x)

`set {_l::*} to all bungeecord players`
`loop {_l::*}:`
`    send "test" to bungeecord player loop-value`

**Comment by Vulqa** [comment]
Same problem, i can't grab my bungeecord servers, he return me "<none>".

`command /lol:
	trigger:
		set {_servers::*} to all of the bungeecord servers
		message "%{_servers::*}%"`

Yet my players have joined the server with the proxy

**Comment by TheLimeGlass** [comment]
Turn debug mode on and send a console log after executing the syntaxes from Bungeecord
