### ISSUE TITLE
GlobalScripts not sending

### ISSUE THREAD

**Issue by SchmiddyTV** [Skungee/Skungee#47]
Hey,

im getting an error when i used your command /staffchat

> 15:36:35 [SEVERE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@4ee203eb, id=145, owner=me.limeglass.skungee.bungeecord.Skungee@1931d99, task=me.limeglass.skungee.bungeecord.sockets.BungeeSockets$1@377fe24d, delay=0, period=0, running=true) encountered an exception
> java.lang.NullPointerException
>     at me.limeglass.skungee.bungeecord.sockets.BungeeSockets$1.run(BungeeSockets.java:111)
>     at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
>     at java.lang.Thread.run(Thread.java:748)

```
function staffChat(message: string):
    loop all players:
        if loop-player has permission "staff.chat":
            message {_message} to loop-player 

command /staffchat [<text>]:
    aliases: /staffchat:staffchat, /sc
    permission: staff.chat
    trigger:
        if arg-1 is set:
            set {_message} to "&7[&cStaff-Chat&7] &9%command sender%:&f %arg-1%"
            loop all bungeecord servers:
                evaluate "staffChat(""%{_message}%"")" on bungeecord server loop-value
        else:
            if {staffchat::toggle::%player's uuid%} is false:
                set {staffchat::toggle::%player's uuid%} to true
                send "&aStaff Chat Chat Enabled"
            else:
                set {staffchat::toggle::%player's uuid%} to false
                send "&cStaff Chat Disabled"
```

Skungee Version: 1.0.9

**Comment by TheLimeGlass** [comment]
Newest version is 1.0.9a

**Comment by SchmiddyTV** [comment]
It doesn't work with 1.0.9a
And there isn't anny error

**Comment by TheLimeGlass** [comment]
This script has to be on other servers too you know right? Or just place it in hlocal scripts

**Comment by SchmiddyTV** [comment]
I've put it in global scripts and it doesn't work...

**Comment by TheLimeGlass** [comment]
Can you post an updated console error with the newer version of 1.0.9a please.

**Comment by ham1255** [comment]
from where  did you get that script?

**Comment by ham1255** [comment]
i did say that in this post https://github.com/Skungee/Skungee/issues/85#issuecomment-527918378

**Comment by ham1255** [comment]
may i have that skript i want to check it out

**Comment by ham1255** [comment]
xd when server reboots it updates the skript files
```
[16:27:48 INFO]: [Skript] Reloading NetworkSkript_chat.sk...
[16:27:48 INFO]: [UltraPermissions] Loading Permission Database...
[16:27:48 INFO]: [UltraPermissions] - 513 Permissions extracted from .jars
[16:27:48 INFO]: [UltraPermissions] - 5255 Permissions downloaded from the Cloud
[16:27:48 INFO]: [Skript] Successfully reloaded NetworkSkript_chat.sk.
[16:27:48 INFO]: [Skungee] GlobalScripts: reloaded script NetworkSkript_chat.sk for this server!
```

**Comment by TheLimeGlass** [comment]
Might be related #105, but the original error posted has been fixed.
