### ISSUE TITLE
global scripts not working

### ISSUE THREAD

**Issue by TwMoTy** [Skungee/Skungee#48]
I put a sk file in BungeeCord/plugins/Skungee/scripts/
but It isn't relay to the spigot servers.
All connected servers are have the Reciever option enabled in the settings.

**Comment by TheLimeGlass** [comment]
The ports for the receivers need to be open.

**Comment by TheLimeGlass** [comment]
Version?

**Comment by ham1255** [comment]
it does happen to me too it just doesn't send the script file tell i restart the bungeecord/waterfal

**Comment by TheLimeGlass** [comment]
If this issue is still present, please make another bug report with the updated Skungee versions and providing more information. We need to be able to figure things out, tell us how you managed to replicate the issue etc within it.
