### ISSUE TITLE
Could not establish connection to Skungee on the Bungeecord.

### ISSUE THREAD

**Issue by dada513** [Skungee/Skungee#54]
Hey!
When i use my script skungee says (in console):
`>[20:21:28 INFO]: [Skungee] Could not establish connection to Skungee on the Bungeecord!

>[20:21:28 INFO]: [Skungee] Attempting to reconnect to Skungee...

>[20:21:28 INFO]: [Skungee] Going into keep alive mode...`

My Script:

`command /gotohub:
    trigger:
        skungee send bungee player to "hub"`

**Comment by TheLimeGlass** [comment]
The credentials do not point to the Bungeecord. Make sure to put in the Spigot Skungee, the correct IP address of the Bungeecord and port defined in the Bungeecord Skungee config. If both the Bungeecord and Spigot are on the same server use localhost as the host option or the direct IP
