### ISSUE TITLE
Server Can't get state

### ISSUE THREAD

**Issue by TestingUser661** [Skungee/Skungee#55]
I have 0 scripts in globalscripts.
Using Skungee latest
Java 8
Linux (ubuntu)

I have made sure that I did not copy and paste the configs and set up the servers and skungees correctly. However, the error still occurs, when sometimes the server cannot check the state of another server, and in my server selectors, they appear offline, and players cannot join any of the servers on my network. This is a huge bug and must be fixed asap. :( 

Simmilar to https://github.com/Skungee/Skungee/issues/51
but could not find this error in my console.

**Comment by TestingUser661** [comment]
Oops, same error...

`[Skungee] Thread: Thread[Craft Scheduler Thread - 0,5,main]
>
[Skungee] End of Error.
>
>
[Skungee] [Skungee] Severe Error:
[Skungee] Socket couldn't be accepted.
>
[Skungee] Something went wrong within Skungee.
[Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
>
[Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues
[Skungee] You can also message one of the Skungee developers this error.
>
[Skungee] Stack trace:
[Skungee] java.net.SocketException: Too many open files (Accept failed)
[Skungee]     at java.net.PlainSocketImpl.socketAccept(Native Method)
[Skungee]     at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
[Skungee]     at java.net.ServerSocket.implAccept(ServerSocket.java:545)
[Skungee]     at java.net.ServerSocket.accept(ServerSocket.java:513)
[Skungee]     at me.limeglass.skungee.spigot.sockets.Reciever$1.run(Reciever.java:44)
[Skungee]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Skungee]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Skungee]     at java.lang.Thread.run(Thread.java:748)
>
[Skungee] Information:
[Skungee]   Skungee: 1.0.9
[Skungee]   Bukkit: 1.8.8-R0.1-SNAPSHOT
[Skungee]   Minecraft: v1_8_R3.
[Skungee]   Java: 1.8.0_191 (Java HotSpot(TM) 64-Bit Server VM 25.191-b12)
[Skungee]   OS: Linux amd64 3.13.0-165-generic
>
[Skungee] Running CraftBukkit: false
>
[Skungee] Thread: Thread[Craft Scheduler Thread - 0,5,main]
>
[Skungee] End of Error.
>`

**Comment by TestingUser661** [comment]
Same as #51

**Comment by TheLimeGlass** [comment]
Duplicate https://github.com/Skungee/Skungee/issues/51
