### ISSUE TITLE
Getting Player Count

### ISSUE THREAD

**Issue by ObeyBeastJj23** [Skungee/Skungee#56]
I have now used i think 4 or so variables to try get the player count of the bungee server, i tried individual proxy/server player counts and then also global ones.
It returns nothing, just blank. I have no idea why it happens and i am like 99% sure my configs are set alright as other commands i have work already.

**Comment by TheLimeGlass** [comment]
If this issue is still present, please make another bug report with the updated Skungee versions and providing more information. We need to be able to figure things out, tell us how you managed to replicate the issue etc within it.
