### ISSUE TITLE
Need assistance connecting Skungee

### ISSUE THREAD

**Issue by Irrelavant** [Skungee/Skungee#57]
I don't seem to understand what's wrong here, both servers are running on the same machine so I set the host to localhost and it still can't connect and just immediately goes into keep alive mode.

Need assistance

Skungee (Bungeecord):
https://pastebin.com/sTYEmdsh

Skungee (Spigot):
https://pastebin.com/sY5qbg2K

**Comment by TheLimeGlass** [comment]
Sorry if this took to long to respond, if you need further help, you can contact me on Discord for faster support `LimeGlass#1070`
