### ISSUE TITLE
console spam. not debug

### ISSUE THREAD

**Issue by hatto966** [Skungee/Skungee#59]
when i run my bungeecord server the skungee plugin is spamming this in all spigot consoles
![image](https://user-images.githubusercontent.com/28825674/58375464-de4b4a00-7f53-11e9-9cd2-f6c7bce74bac.png) and this in the bungeecord console 
![image](https://user-images.githubusercontent.com/28825674/58375477-22d6e580-7f54-11e9-81ac-42a8529ebcd9.png).

**Comment by TheLimeGlass** [comment]
I need versions, config.yml of bungee, versions of bungee and your Skungee.yml's...

**Comment by hatto966** [comment]
here is the bungeecord's skungee config & version https://pastebin.com/GXu173TY

here is the bungeecord general config https://pastebin.com/8YxAq2n5 and the version is 1.8

**Comment by TheLimeGlass** [comment]
Increase your heartbeat, it's not spam, that's your server losing connection and connecting again either because of lag, or low internet quality.

**Comment by TheLimeGlass** [comment]
Try Bungeecord 1.14, it's for all MC versions, 1.14 is just the name.
