### ISSUE TITLE
Spamming Console Problem / Causing skripts problems

### ISSUE THREAD

**Issue by ChifuyuNee** [Skungee/Skungee#60]
Heya! I have a problem with Skungee. On my BungeeCord console I've been spamming this error for 1 week and now sometimes bungeecord interactions

> 14:25:12 [INFO] [Skungee] [Skungee] Severe Error: [Unknown host: /127.0.0.1:10003]
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] Something went wrong within Skungee.
> 14:25:12 [INFO] [Skungee] Please report this error to the developers of Skungee so we can fix this from happening in the future.
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] Report this at https://github.com/TheLimeGlass/Skungee/issues. You can also message one of the Skungee developers.
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] Stack trace:
> 14:25:12 [INFO] [Skungee] java.net.UnknownHostException: 2af1347a-c06f-498a-8840-9501dce5c91d: 2af1347a-c06f-498a-8840-9501dce5c91d: Name or service not known
> 14:25:12 [INFO] [Skungee] at java.net.InetAddress.getLocalHost(InetAddress.java:1506)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:30)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeHandler.callPacket(SkungeeHandler.java:98)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:92)
> 14:25:12 [INFO] [Skungee] at java.lang.Thread.run(Thread.java:748)
> 14:25:12 [INFO] [Skungee] Caused by: java.net.UnknownHostException: 2af1347a-c06f-498a-8840-9501dce5c91d: Name or service not known
> 14:25:12 [INFO] [Skungee] at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
> 14:25:12 [INFO] [Skungee] at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
> 14:25:12 [INFO] [Skungee] at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
> 14:25:12 [INFO] [Skungee] at java.net.InetAddress.getLocalHost(InetAddress.java:1501)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.handlers.HeartbeatHandler.handlePacket(HeartbeatHandler.java:30)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.handlercontroller.SkungeeHandler.callPacket(SkungeeHandler.java:98)
> 14:25:12 [INFO] [Skungee] at me.limeglass.skungee.bungeecord.sockets.BungeeRunnable.run(BungeeRunnable.java:92)
> 14:25:12 [INFO] [Skungee] at java.lang.Thread.run(Thread.java:748)
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] Information:
> 14:25:12 [INFO] [Skungee] Skungee: 1.0.9
> 14:25:12 [INFO] [Skungee] Bungee: git:BungeeCord-Bootstrap:1.14-SNAPSHOT:8fda060:1413
> 14:25:12 [INFO] [Skungee] Game version: 1.8.x-1.14.x
> 14:25:12 [INFO] [Skungee] Protocol version: 485
> 14:25:12 [INFO] [Skungee] Java: 1.8.0_212 (OpenJDK 64-Bit Server VM 25.212-b01)
> 14:25:12 [INFO] [Skungee] OS: Linux amd64 4.4.0-146-generic
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] Thread: Thread[Thread-697646,5,Skungee]
> 14:25:12 [INFO] [Skungee] Cause: [Unknown host: /127.0.0.1:10003]
> 14:25:12 [INFO]
> 14:25:12 [INFO] [Skungee] End of Error.
> 14:25:12 [INFO]

That make problems with some global scripts (for fix that i need to restart all of my network but that still here after..)

Exemple : (support)
```
command /support [<text>]:
	trigger:
		if arg 1 is set:
			send "&6Electryon &7&l» &aVotre demande à bien été prise en compte et sera traîtée sous peu.."
			send bungeecord message "{@prefix}%player's prefix%%player% &2→ &r%arg-1%" to the bungeecord channel "support"
			send "&aContenu &7de votre message : &r%arg-1%" to player
		if arg 1 is not set:
			send "&6Electryon &8&l» &cErreur ! Usage correct : &6/&dsupport &7<&avotre demande&7>"
			send "&c&lNote &7: &bTout abus &bdu &a/&dsupport &best &csanctionable &b!"
		if player has permission "staffchat":
			stop

on skungee message from channel "support":
	loop all players:
		if loop-player has permission "staffchat":
			send coloured skungee message to loop-player
```

The bungee message doesn't work in game (no errors in console server/bungee)

I don't know why that make this error & that problematic

**Comment by TheLimeGlass** [comment]
You out the uuid of the bungee as the server host? You need to put the server address.

**Comment by ChifuyuNee** [comment]
That make same error with localhost/localip/ip for the ovh server

**Comment by HevelMc** [comment]
We use pterodactyl with a Custom Network Interface

(from https://pterodactyl.io/daemon/configuration.html#custom-network-interfaces)

and the same bug occurs with the following ips:
- 176.31.107.225
- 172.18.0.1 (docker ip)
- 127.0.0.1
- localhost
- 0.0.0.0

**Comment by ChifuyuNee** [comment]
@TheLimeGlass ?

**Comment by TheLimeGlass** [comment]
pterodactyl seems to always been an issue with Skungee, I have had plans to remake the connection, maybe add an address to bind too?

**Comment by ChifuyuNee** [comment]
That's can be fix when ?

**Comment by TheLimeGlass** [comment]
You can now define the ip address to bind to in the Bungeecord Skungee configuration.
