### ISSUE TITLE
Skungee Crashing Servers and Proxy Skungee Stops Working

### ISSUE THREAD

**Issue by Dakotaa** [Skungee/Skungee#61]
Skungee seems to be crashing my servers (one server crashed with a skungee error and then the other crashed a minute later). From the crash error, it looks like it's crashing when trying to get a network variable on player login.

After the crashes, the servers don't seem to connect to the proxy skungee once they are restarted, and a bungee restart is required for skungee to be working properly again.

Crash log: https://pastebin.com/t6BiJ3Bm

**Comment by TheLimeGlass** [comment]
How much ram are you allocating to the Bungeecord, also please provide your Skungee and Waterfall versions, try the 1.14-SNAPSHOT bungeecord and see if that fixes it. Waterfall does work with Skungee but it's not supported.

I will be closing your other issue, and reference it here. #62

**Comment by Dakotaa** [comment]
This has been happening with anywhere from 2GB-10GB allocated to the proxy, as well as with both BungeeCord and Waterfall. Currently running Waterfall with 10GB (I know that's much more memory than the proxy needs, but I wanted to see if allocating a ton of memory would make any difference) and it just happened a few minutes ago. When it happens, the proxy continues to run fine, and checking the memory available on the proxy shows 2+ GB of RAM free. It seems to be just be Skungee that stops working.

Running Skungee 1.0.9 and Waterfall 1.14 #284, but I'll give the latest BungeeCord a try.

**Comment by Dakotaa** [comment]
Hasn't happened again since switching back to Bungee and reducing ram to 2.5GB. However, I'm still getting the issue with network variables locking up the server, which pretty much causes a crash as it will bring the TPS down to ~5.

**Comment by Dakotaa** [comment]
Nevermind, it is still happening, and causing server crashes as well.

**Comment by Dakotaa** [comment]
Still getting this lag spike issue at least once every day
`22.07 13:50:16 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-639 (MC: 1.13.2) ---
22.07 13:50:16 [Server] ERROR The server has not responded for 10 seconds! Creating thread dump
22.07 13:50:16 [Server] ERROR ------------------------------
22.07 13:50:16 [Server] ERROR Server thread dump (Look for plugins here before reporting to Paper!):
22.07 13:50:16 [Server] ERROR ------------------------------
22.07 13:50:16 [Server] ERROR Current Thread: Server thread
22.07 13:50:16 [Server] ERROR PID: 33 | Suspended: false | Native: true | State: RUNNABLE
22.07 13:50:16 [Server] ERROR Stack:
22.07 13:50:16 [Server] ERROR java.net.SocketInputStream.socketRead0(Native Method)
22.07 13:50:16 [Server] ERROR java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
22.07 13:50:16 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:171)
22.07 13:50:16 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:141)
22.07 13:50:16 [Server] ERROR java.net.SocketInputStream.read(SocketInputStream.java:224)
22.07 13:50:16 [Server] ERROR java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2641)
22.07 13:50:16 [Server] ERROR java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:2948)
22.07 13:50:16 [Server] ERROR java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
22.07 13:50:16 [Server] ERROR java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1540)
22.07 13:50:16 [Server] ERROR java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
22.07 13:50:16 [Server] ERROR me.limeglass.skungee.spigot.sockets.Sockets.send_i(Sockets.java:184)
22.07 13:50:16 [Server] ERROR me.limeglass.skungee.spigot.sockets.Sockets.send(Sockets.java:112)
22.07 13:50:16 [Server] ERROR me.limeglass.skungee.spigot.elements.expressions.ExprNetworkVariable.change(ExprNetworkVariable.java:124)
22.07 13:50:16 [Server] ERROR ch.njol.skript.effects.EffChange.execute(EffChange.java:284)
22.07 13:50:16 [Server] ERROR ch.njol.skript.lang.Effect.run(Effect.java:52)
22.07 13:50:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
22.07 13:50:16 [Server] ERROR ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
22.07 13:50:16 [Server] ERROR ch.njol.skript.effects.Delay$1.run(Delay.java:109)
22.07 13:50:16 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
22.07 13:50:16 [Server] ERROR org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449)
22.07 13:50:16 [Server] ERROR net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010)
22.07 13:50:16 [Server] ERROR net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
22.07 13:50:16 [Server] ERROR net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
22.07 13:50:16 [Server] ERROR net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
22.07 13:50:16 [Server] ERROR java.lang.Thread.run(Thread.java:748)
22.07 13:50:16 [Server] ERROR ------------------------------
22.07 13:50:16 [Server] ERROR --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
22.07 13:50:16 [Server] ERROR ------------------------------`

**Comment by Dakotaa** [comment]
Still having similar issues - Skungee completely stops working across all servers, and crashes one of my servers with an OutOfMemory error.

**Comment by Govindass** [comment]
I think this could be happening due to accessing network variables before server is connected to the bungee

**Comment by TheLimeGlass** [comment]
I'm pretty sure it's just packet loss.

**Comment by Dakotaa** [comment]
Has this been improved at all? I'd like to use Skungee again, but I want to be sure this problem won't appear again before I start moving everything over to Skungee.

**Comment by TheLimeGlass** [comment]
It shouldn't be crashing the server, Skungee has been running on async since about 1.0.9. This error is fairly old, and if it still continues let us know in this issue ticket, I personally see all replies on issues.

**Comment by TheLimeGlass** [comment]
Please make new issue if continues, thanks.
