### ISSUE TITLE
Events called asynchronously no longer works on bukkit 1.14

### ISSUE THREAD

**Issue by Tinkot** [Skungee/Skungee#63]
This only applies to 1.0.9a

I've tried to remove some of the event from the source but the problem is that all evens are called asynchronously. Hope you can resolve the issue, i want to primarily use skungee for its new api 🙂

here is a stacktrace:
https://i.ibb.co/31yky2S/Schermafbeelding-2019-07-14-om-16-40-11.png

**Comment by Tinkot** [comment]
So i was working on one of my own plugins and came across the same problem. You can call the super class with true to allow the event to be called asynchronously. 

example:
```
public MyEvent() {
    super(true); 
}
```

found at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/Event.html#Event-boolean-

**Comment by ham1255** [comment]
#70

**Comment by TheLimeGlass** [comment]
Fixed in 1.0.9b
