### ISSUE TITLE
Skungee (network variables?) locking server 

### ISSUE THREAD

**Issue by Dakotaa** [Skungee/Skungee#64]
Skungee seems to causing massive lag spikes that give the "server has stopped responding" messages in console. Looks like it's related to network variables.

Thread dump:
https://pastebin.com/APU2CXQq

Also getting this error on the proxy: https://pastebin.com/5SsqpY8E

**Comment by TheLimeGlass** [comment]
I think I have seen this before, It has something to do with ProtocolSupport. I need to check it out sometime, but it's not Skungee's fault.

**Comment by TheLimeGlass** [comment]
Duplicate #61
