### ISSUE TITLE
Get 1 skript file, work in 2 servers

### ISSUE THREAD

**Issue by Romek003** [Skungee/Skungee#66]
Hi,

I want to create 1 file that can work in 2 servers connected with bungeecord en Skungee. Also i want to use network variables for that.

Can somebody help me with getting that done?

~Romek

**Comment by ham1255** [comment]
create the skript file in bungeecord by going to bungeecord folder/plugins/skungee/scripts

**Comment by TheLimeGlass** [comment]
You can also put scripts in `plugins/Skungee/scripts/hub/` and all those scripts will be in the hub only.
