### ISSUE TITLE
Skungee Console Errors - Address related

### ISSUE THREAD

**Issue by Arcantiz** [Skungee/Skungee#69]
Hey there, I'm having a bit of an odd issue and I'm not 100% how to solve it, I'm sorry if this is really time-wasting but I'm at my wit's end here.

The issue is much similar to the problem in this [forum thread](https://forums.skunity.com/threads/skungee-connect-to-server.8178/)

Now I've tried to change the config of the bungeecord multiple times I've upgraded to the newest version available at md_5's jenkins I've removed plugins to see if that changed anything and I'm still getting [this error spammed in my console](https://pastebin.com/ApFT97xF).

When I remove the server it can't connect to (I assume) it doesn't spam this issue however I have 3 servers (Hub, Kitpvp, Guilds) In the Error you will notice the startup when I remove Kitpvp is only mentioning Hub and not Guilds. However even when the error is being spammed everything to do with Skungee works I can connect to the other servers just fine and there is no noticeable delay.

I'm really confused but I would like to get rid of the error from my console.

Links:
[Bungeecord Config](https://pastebin.com/tT3FuL43)
[Skungee-Bungeecord](https://pastebin.com/fYs9Qnz0)
[Skungee-Spigot Servers](https://pastebin.com/exhKcpPF)
[Without Kitpvp in my Bungeecord Config-Console](https://pastebin.com/DSVzS8u9)

**Comment by TheLimeGlass** [comment]
You can now bind an address to an IP in the newest versions, will help your issue.
