### ISSUE TITLE
A lot of oppened ports...

### ISSUE THREAD

**Issue by GlobooX** [Skungee/Skungee#71]
Hi, i have big problem. I have 6 servers connected to one bungee. On each server and Bungee i have Skungee installed.. 
Sometimes i cant start minecraft server becouse port is alredy in use (probably by Skungee Receiver)
Here is list of ports: https://pastebin.com/YRc3TSqm

Everythings is ok, but after ~8h all connected servers lost connection with bungee.. Then i cant use any SKUNGEE effects, expressions and events. 

Here is error on one of the spigot server connected with bungee: https://pastebin.com/50K2DBhL

PS:
Here is my part of config
https://pastebin.com/Y03wskH4

**Comment by TheLimeGlass** [comment]
Had this been fixed in 1.0.10a?

**Comment by GlobooX** [comment]
@TheLimeGlass yes, it is fixed but i have another problem. 
When i restart "server1" then if i check online status of "server1" on server2 then i have OFFLINE.
I need to restart bungee to "server1" online status back to previous.

**Comment by TheLimeGlass** [comment]
Ya i'm aware of that issue, the heartbeat packet isn't responding the way it should be. 1.1.0 fixes that issue, but it also has critical changes to Skungee in which case it's not published public. There is a branch for 1.1.0 for those interested. I have been working on making it stable enough for public release in the upcoming updates.

Relating issue would be #46
