### ISSUE TITLE
Network variables seem to freeze the server

### ISSUE THREAD

**Issue by Govindass** [Skungee/Skungee#72]
I have been having this issue for a while, happens usually on server restart (not always), but sometimes also during normal server running, have happened with 0 players online when no network variables are being interacted with

the server just freezes and a manual restart needed to get it back working
this stacktrace is thrown and kept being spammed over and over again until server's thread completely freezes:

[09:31:54] [Server thread/INFO]: [NetworkInterceptor] Intercepted outgoing connection to host '91.211.246.120' #connection done by Skungee
[09:31:58] [Paper Watchdog Thread/ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[09:31:58] [Paper Watchdog Thread/ERROR]: The server has not responded for 4 seconds! Creating thread dump
[09:31:58] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:31:58] [Paper Watchdog Thread/ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
```
[09:31:58] [Paper Watchdog Thread/ERROR]: ------------------------------
[09:31:58] [Paper Watchdog Thread/ERROR]: Current Thread: Server thread
[09:31:58] [Paper Watchdog Thread/ERROR]:     PID: 19 | Suspended: false | Native: false | State: RUNNABLE
[09:31:58] [Paper Watchdog Thread/ERROR]:     Stack:
java.util.WeakHashMap.get(WeakHashMap.java:403)
 		ch.njol.skript.variables.Variables.setVariable(Variables.java:319)
 		ch.njol.skript.lang.Variable.set(Variable.java:368)
 		ch.njol.skript.lang.Variable.change(Variable.java:428)
 		ch.njol.skript.effects.EffChange.execute(EffChange.java:271)
 		ch.njol.skript.lang.Effect.run(Effect.java:52)
 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
 		ch.njol.skript.lang.Trigger.execute(Trigger.java:55)
 		com.btk5h.skriptmirror.skript.custom.expression.CustomExpression.getByStandard(CustomExpression.java:90)
 		com.btk5h.skriptmirror.skript.custom.expression.CustomExpression.getAll(CustomExpression.java:84)
 		com.btk5h.skriptmirror.skript.custom.expression.CustomExpression.getArray(CustomExpression.java:65)
 		ch.njol.skript.lang.VariableString.toString(VariableString.java:440)
 		ch.njol.skript.lang.VariableString.getSingle(VariableString.java:599)
 		ch.njol.skript.lang.VariableString.getSingle(VariableString.java:1)
 		ch.njol.skript.effects.EffMessage.execute(EffMessage.java:90)
 		ch.njol.skript.lang.Effect.run(Effect.java:52)
 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
 		ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:89)
 		ch.njol.skript.effects.Delay$1.run(Delay.java:101)
 		org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
 		org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
 		net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
 		net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
 		net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
 		net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
 		java.lang.Thread.run(Thread.java:748)
```

**Comment by TheLimeGlass** [comment]
Can you post the code you are using from skript-mirror? This is not Skungee's normal behavior and could be in conflict with skript-mirror. Keep in mind that Skungee network variables are handled in an asynchronous thread, and you could potentially be syncing it to the server while it does that with skript-mirror.

**Comment by Govindass** [comment]
I'm not using anything skungee related with skript-mirror

**Comment by TheLimeGlass** [comment]
This error report serves no help to us, marking as duplicate. https://github.com/Skungee/Skungee/issues/61
