### ISSUE TITLE
Network Vriables gives <none> very often

### ISSUE THREAD

**Issue by Mr-Vuda** [Skungee/Skungee#73]
Hi, i have this problem. When i use network variables it gives <none> very very often, when i set players prefix to like owner and when he is chat, sometimes it say <none> nUKEmAN4: msg in chat. And i did a little test, look: http://nukedgalaxy.ga/video/networkvariable.mp4 How to fix it? Global script are connected and refresh every time, in console says it is connected to hub etc... Thanks

**Comment by Mr-Vuda** [comment]
EDIT: Also, no error in console

**Comment by ham1255** [comment]
yep it does some times for me

**Comment by Mr-Vuda** [comment]
Well, i dont think LimeGlass will support this issuse, He has nexted it...

**Comment by ham1255** [comment]
...?

**Comment by Mr-Vuda** [comment]
@ham1255 ham1255 i found a fix, contact me on discord nUKEmAN4#3346 or via my website www.nukedgalaxy.ga , a Vrganj helped me.

**Comment by TheLimeGlass** [comment]
You shouldn't be calling network variables so frequently, it's hard on the server to send and wait for a response, which can lower server performance.

**Comment by Mr-Vuda** [comment]
Oh, maybe i should not use %network variable {chat::prefix::%player%} then

**Comment by Mr-Vuda** [comment]
I mean in chat, on chat

**Comment by TheLimeGlass** [comment]
You can save it to a server variable when they first join/switch servers in that case.

**Comment by Mr-Vuda** [comment]
Yea, i willl. Thank you! You can close this. Do you maybe have on plan to fix it somehow or add better system?

**Comment by TheLimeGlass** [comment]
Probably, everything can always be improved to near optimal
