### ISSUE TITLE
Getting an internal error on command

### ISSUE THREAD

**Issue by HerozOfficial** [Skungee/Skungee#93]
command /stst <string>:
    trigger:
        skungee send "%arg-1%" to all of the bungeecord players
        set {_y} to size of all of the connected bungeecord servers
        send "%{_y}%" to event-player

https://pastebin.com/QmS2QQde

Skript: 2.3.6
Skungee: 1.0.11

**Comment by TheLimeGlass** [comment]
Fixed in the next version.
