### ISSUE TITLE
GLOBAL SKRIPTS NOT WORKING

### ISSUE THREAD

**Issue by skptical** [Skungee/Skungee#99]
I recently installed skungee, I setup the ip and port for both spigot and bungee and it was setup fully and in the console aswell as bungeecord it said it was connected!

I tried creating a global skript by going into the directory:

root\plugins\skungee\scripts

And adding a skript, yet it doesn't work?

**Comment by antoinech2** [comment]
I have a similar problem, scripts in folder are send to servers only if I restart the BungeeCord server, it is not automatic. I don't know if it is a bug or not. (I have the same ports in all Skungee's config files)

**Comment by TheLimeGlass** [comment]
#47
